name: Buf Lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  buf-lint:
    name: Buf Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
